services:
  postgres:
    image: postgres:16.1
    container_name: wiredcraft-psql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql