// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

func New(db DBTX) *Conn {
	return &Conn{
		ctx: context.Background(),
		db:  db,
	}
}

type Conn struct {
	ctx context.Context
	db  DBTX
}

func (q *Conn) WithTx(tx pgx.Tx) *Conn {
	return &Conn{
		db: tx,
	}
}
