// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID
	Name        string
	Dob         pgtype.Date
	Description string
	CreatedAt   pgtype.Timestamp
}

type UserAddress struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	AddressLine1 string
	AddressLine2 pgtype.Text
	City         string
	State        string
	PostalCode   string
	Country      string
	CreatedAt    pgtype.Timestamp
}
